In [ ]:
import torch

x= torch.rand(2, 3)
x

tensor([[0.8236, 0.5533, 0.0191],
        [0.4942, 0.1263, 0.4529]])

In [ ]:
x= torch.randn(2, 3)
x

tensor([[ 0.4699, -0.4371,  1.8170],
        [ 0.4106,  1.9871, -0.6082]])

In [ ]:
x= torch.randperm(5)
x

tensor([0, 3, 1, 2, 4])

In [ ]:
x = torch.tensor([[1., 2.], [3., 4.]])
y = torch.randn_like(x)

print(y)

tensor([[-0.5267,  0.0665],
        [-1.6117, -0.1370]])


In [ ]:
# torch.randint() : 지정 범위의 정수를 랜덤 생성
x = torch.randint(0, 10, (2, 3))
x

tensor([[8, 5, 0],
        [3, 1, 5]])

In [ ]:
x = torch.tensor([[1., 2.], [3., 4.]])
y = torch.randn_like(x)
y

tensor([[ 0.3855,  0.4280],
        [ 0.5165, -0.2397]])

In [ ]:
x= torch.zeros(2, 3)
x

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
x=torch.ones(2, 3)
x

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
x=torch.arange(0, 3, step=0.5)
x

tensor([0.0000, 0.5000, 1.0000, 1.5000, 2.0000, 2.5000])

In [ ]:
x= torch.FloatTensor(2, 3)
x

tensor([[       nan, 4.4714e-41,        nan],
        [4.4714e-41, 4.4842e-44, 0.0000e+00]])

In [ ]:
x=torch.FloatTensor([12, 35])
x

tensor([12., 35.])

In [ ]:
x=x.type_as(torch.IntTensor())
x

tensor([12, 35], dtype=torch.int32)

In [ ]:
import numpy as np
x1 = np.ndarray(shape=(2, 3), dtype=int, buffer=np.array([1, 2, 3, 4, 5, 6]))
x1

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
x2 = torch.from_numpy(x1)
x2

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
x3 = x2.numpy()
x3

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
x = torch.FloatTensor([[1, 2, 3], [4, 5, 6]])
x

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [10]:
import torch

print(torch.cuda.is_available())

True


In [12]:
import torch

print(torch.__version__)
print(torch.cuda.is_available())

x = torch.tensor([1, 2, 3])

print("x :", x.device)

x_gpu = x.to("cuda")

print("x_gpu :", x_gpu.device)
print(x_gpu)

x_cpu = x_gpu.cpu()

print("x_cpu :", x_cpu.device)
print(x_cpu)

2.11.0+cu128
True
x : cpu
x_gpu : cuda:0
tensor([1, 2, 3], device='cuda:0')
x_cpu : cpu
tensor([1, 2, 3])


In [15]:
x=torch.FloatTensor(10, 12, 2, 3)

x.size()[:], x

(torch.Size([10, 12, 2, 3]),
 tensor([[[[ 1.4013e-43,  1.5414e-44,  0.0000e+00],
           [ 0.0000e+00,  0.0000e+00,  0.0000e+00]],
 
          [[ 0.0000e+00,  0.0000e+00,  0.0000e+00],
           [ 0.0000e+00,  0.0000e+00,  0.0000e+00]],
 
          [[ 0.0000e+00,  0.0000e+00,  0.0000e+00],
           [ 0.0000e+00,  0.0000e+00,  0.0000e+00]],
 
          [[ 0.0000e+00,  0.0000e+00,  0.0000e+00],
           [ 0.0000e+00,  0.0000e+00,  0.0000e+00]],
 
          [[ 0.0000e+00,  0.0000e+00,  0.0000e+00],
           [ 0.0000e+00,  0.0000e+00,  0.0000e+00]],
 
          [[ 0.0000e+00,  0.0000e+00,  0.0000e+00],
           [ 0.0000e+00,  0.0000e+00,  0.0000e+00]],
 
          [[ 0.0000e+00,  0.0000e+00,  0.0000e+00],
           [ 0.0000e+00,  0.0000e+00,  0.0000e+00]],
 
          [[ 0.0000e+00,  0.0000e+00,  0.0000e+00],
           [ 0.0000e+00,  0.0000e+00,  0.0000e+00]],
 
          [[ 0.0000e+00,  0.0000e+00,  0.0000e+00],
           [ 0.0000e+00,  0.0000e+00,  0.0000e+00]],
 
        

In [ ]:
x= torch.randn(4, 3)
out = torch.index_select(x, 0, torch.LongTensor([0, 3]))
x, out

(tensor([[ 0.0136,  0.3422,  1.1849],
         [-0.5730,  0.5489, -0.5784],
         [ 1.1734,  0.4189, -1.1875],
         [ 0.5139, -1.3733, -1.4510]]),
 tensor([[ 0.0136,  0.3422,  1.1849],
         [ 0.5139, -1.3733, -1.4510]]))

In [ ]:
x[:, 0], x[0, :], x[0:2,0:2]

(tensor([ 0.0136, -0.5730,  1.1734,  0.5139]),
 tensor([0.0136, 0.3422, 1.1849]),
 tensor([[ 0.0136,  0.3422],
         [-0.5730,  0.5489]]))

In [ ]:
x= torch.randn(2,3)
mask = torch.BoolTensor([[False, False, True], [False, True, False]])
out = torch.masked_select(x, mask)
x, mask, out

(tensor([[-0.1580,  0.8312,  0.6699],
         [ 1.3099, -0.3721, -0.2333]]),
 tensor([[False, False,  True],
         [False,  True, False]]),
 tensor([ 0.6699, -0.3721]))

In [ ]:
x= torch.FloatTensor([[1,2,3],[4,5,6]])
y= torch.FloatTensor([[-1,-2,-3],[-4,-5,-6]])

z1 = torch.cat([x,y],dim=0)
z2 = torch.cat([x,y],dim=1)

x, y, z1, z2

(tensor([[1., 2., 3.],
         [4., 5., 6.]]),
 tensor([[-1., -2., -3.],
         [-4., -5., -6.]]),
 tensor([[ 1.,  2.,  3.],
         [ 4.,  5.,  6.],
         [-1., -2., -3.],
         [-4., -5., -6.]]),
 tensor([[ 1.,  2.,  3., -1., -2., -3.],
         [ 4.,  5.,  6., -4., -5., -6.]]))

In [ ]:
x= torch.FloatTensor([[1,2,3],[4,5,6]])
x_stack = torch.stack([x, x, x, x], dim=0)
x_stack

tensor([[[1., 2., 3.],
         [4., 5., 6.]],

        [[1., 2., 3.],
         [4., 5., 6.]],

        [[1., 2., 3.],
         [4., 5., 6.]],

        [[1., 2., 3.],
         [4., 5., 6.]]])

In [24]:
x = torch.tensor([
    [1,2],
    [3,4],
    [5,6],
    [7,8]
])
a, b = torch.chunk(x, 2, dim=0)
c, d = torch.chunk(x, 2, dim=1)

a, b, c, d

(tensor([[1, 2],
         [3, 4]]),
 tensor([[5, 6],
         [7, 8]]),
 tensor([[1],
         [3],
         [5],
         [7]]),
 tensor([[2],
         [4],
         [6],
         [8]]))

In [ ]:
z1 = torch.arange(16).reshape(4,4)
x1, x2 = torch.split(z1, 2, dim=0)
y1 = torch.split(z1, 2, dim=1)
z1, x1, x2, y1

(tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11],
         [12, 13, 14, 15]]),
 tensor([[0, 1, 2, 3],
         [4, 5, 6, 7]]),
 tensor([[ 8,  9, 10, 11],
         [12, 13, 14, 15]]),
 (tensor([[ 0,  1],
          [ 4,  5],
          [ 8,  9],
          [12, 13]]),
  tensor([[ 2,  3],
          [ 6,  7],
          [10, 11],
          [14, 15]])))

In [ ]:
x1 = torch.FloatTensor(10, 1, 3, 4)
x2 = torch.squeeze(x1)
x1.size(), x2.size()

(torch.Size([10, 1, 3, 4]), torch.Size([10, 3, 4]))

In [ ]:
x1 = torch.FloatTensor(10, 3, 4)
x2 = torch.unsqueeze(x1, dim=0)
x1.size(), x2.size()

(torch.Size([10, 3, 4]), torch.Size([1, 10, 3, 4]))

In [ ]:
import torch.nn.init as init
x1 = init.uniform_(torch.FloatTensor(3, 4), a=0, b=9)
x2 = init.normal(torch.FloatTensor(10, 3, 4), std=0.2)
x3 = init.constant_(torch.FloatTensor(2, 3), 3.145)
x1, x2, x3

/tmp/ipykernel_2440/3790887773.py:3: FutureWarning: `nn.init.normal` is now deprecated in favor of `nn.init.normal_`.
  x2 = init.normal(torch.FloatTensor(10, 3, 4), std=0.2)


(tensor([[1.7441, 4.2370, 3.5856, 6.7335],
         [7.9695, 3.1716, 8.9465, 2.7845],
         [5.4902, 7.5013, 6.7823, 2.9309]]),
 tensor([[[ 0.1731, -0.1021,  0.0750, -0.2302],
          [-0.0242,  0.0160, -0.2776,  0.0721],
          [-0.1796,  0.4217, -0.1668,  0.0177]],
 
         [[ 0.0033, -0.0289,  0.1784,  0.1561],
          [ 0.1429, -0.1232, -0.0408, -0.0639],
          [-0.0846, -0.1577, -0.3236, -0.0094]],
 
         [[-0.3478,  0.1190, -0.1323, -0.1599],
          [-0.0114, -0.2204, -0.2094, -0.1734],
          [ 0.2114,  0.1214,  0.0617,  0.2605]],
 
         [[ 0.0641, -0.0021,  0.3196, -0.0325],
          [ 0.0750, -0.0655, -0.3273,  0.0705],
          [-0.2573,  0.1465,  0.0066, -0.1772]],
 
         [[-0.1394, -0.2469,  0.0867,  0.0901],
          [-0.0555,  0.0893, -0.0368,  0.2074],
          [-0.0294,  0.0570, -0.1449, -0.1699]],
 
         [[ 0.0422,  0.0009,  0.0059,  0.0608],
          [-0.0702,  0.3531,  0.3519,  0.2061],
          [ 0.1327,  0.3031, -0.2360, 

In [ ]:
x1 = torch.FloatTensor(([1, 2, 3], [4, 5, 6]))
x2 = torch.FloatTensor(([1, 2, 3], [4, 5, 6]))
add = torch.add(x1, x2)
x1, x2, add, x1 + x2, x1 -2, add

(tensor([[1., 2., 3.],
         [4., 5., 6.]]),
 tensor([[1., 2., 3.],
         [4., 5., 6.]]),
 tensor([[ 2.,  4.,  6.],
         [ 8., 10., 12.]]),
 tensor([[ 2.,  4.,  6.],
         [ 8., 10., 12.]]),
 tensor([[-1.,  0.,  1.],
         [ 2.,  3.,  4.]]),
 tensor([[ 2.,  4.,  6.],
         [ 8., 10., 12.]]))

In [ ]:
x2 = torch.add(x1, 10)
x1, x2, x1 + 10, x1 - 10, x2

(tensor([[1., 2., 3.],
         [4., 5., 6.]]),
 tensor([[11., 12., 13.],
         [14., 15., 16.]]),
 tensor([[11., 12., 13.],
         [14., 15., 16.]]),
 tensor([[-9., -8., -7.],
         [-6., -5., -4.]]),
 tensor([[11., 12., 13.],
         [14., 15., 16.]]))

In [ ]:
x1 = torch.FloatTensor(([1, 2, 3], [4, 5, 6]))
x2 = torch.FloatTensor(([1, 2, 3], [4, 5, 6]))
x3 = torch.torch.mul(x1, x2)
x3, x1 * x2

(tensor([[ 1.,  4.,  9.],
         [16., 25., 36.]]),
 tensor([[ 1.,  4.,  9.],
         [16., 25., 36.]]))

In [ ]:
x4 = torch.mul(x1, 10)
x4, x1 * 10

(tensor([[10., 20., 30.],
         [40., 50., 60.]]),
 tensor([[10., 20., 30.],
         [40., 50., 60.]]))

In [ ]:
x5 = torch.div(x1, 5)
x5, x1 / 5

(tensor([[0.2000, 0.4000, 0.6000],
         [0.8000, 1.0000, 1.2000]]),
 tensor([[0.2000, 0.4000, 0.6000],
         [0.8000, 1.0000, 1.2000]]))

In [ ]:
x1 = torch.FloatTensor(3, 4)
x1, torch.pow(x1, 2)

(tensor([[7.1239e-28, 0.0000e+00, 7.1099e-28, 0.0000e+00],
         [1.1210e-43, 0.0000e+00, 8.9683e-44, 0.0000e+00],
         [7.0830e-28, 0.0000e+00, 7.1080e-28, 0.0000e+00]]),
 tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]))

In [ ]:
x1 = torch.FloatTensor(3, 4)
out = torch.exp(x1)
x1, out

(tensor([[0.0000e+00, 0.0000e+00, 7.1249e-28, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
         [1.4013e-45, 0.0000e+00, 1.6816e-44, 0.0000e+00]]),
 tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]))

In [ ]:
out = torch.log(x1)
x1, out

(tensor([[0.0000e+00, 0.0000e+00, 7.1249e-28, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
         [1.4013e-45, 0.0000e+00, 1.6816e-44, 0.0000e+00]]),
 tensor([[     -inf,      -inf,  -62.5088,      -inf],
         [     -inf,      -inf,      -inf,      -inf],
         [-103.2789,      -inf, -100.7940,      -inf]]))

In [ ]:
x1 = torch.FloatTensor(3, 4)
x2 = torch.FloatTensor(4, 5)
out = torch.mm(x1, x2)
x1, x2, out

(tensor([[6.0120e-41, 0.0000e+00, 7.1938e-28, 0.0000e+00],
         [1.1210e-43, 0.0000e+00, 8.9683e-44, 0.0000e+00],
         [7.0967e-28, 0.0000e+00, 2.4624e-17, 4.3311e-41]]),
 tensor([[ 7.0871e-28,  0.0000e+00,  0.0000e+00,  0.0000e+00,  4.3265e-28],
         [ 0.0000e+00, -4.3618e-34,  4.3311e-41,  4.3265e-28,  0.0000e+00],
         [ 2.0319e-43,  0.0000e+00,  7.2027e-28,  0.0000e+00,  7.1077e-28],
         [ 0.0000e+00, -4.7587e-34,  4.3311e-41,  0.0000e+00,  0.0000e+00]]),
 tensor([[0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, -0.0000e+00, 1.8217e-44, 0.0000e+00, 1.6816e-44]]))

In [ ]:
x1 = torch.FloatTensor(10, 3, 4)
x2 = torch.FloatTensor(10, 4, 5)
out = torch.bmm(x1, x2)
x1, x2, out

(tensor([[[1.4013e-45, 1.4013e-45, 7.0065e-45, 1.4013e-44],
          [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
          [1.4854e-43, 4.2039e-45, 1.4013e-45, 1.4013e-45]],
 
         [[7.0065e-45, 3.0829e-44, 0.0000e+00, 0.0000e+00],
          [0.0000e+00, 0.0000e+00, 1.4013e-43, 0.0000e+00],
          [1.4013e-45, 1.4013e-45, 3.2230e-44, 3.5032e-44]],
 
         [[0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
          [1.4013e-43, 1.4013e-45, 1.4013e-45, 1.4013e-45],
          [3.7835e-44, 3.9236e-44, 0.0000e+00, 0.0000e+00]],
 
         [[0.0000e+00, 0.0000e+00, 1.4013e-43, 2.8026e-45],
          [1.4013e-45, 1.4013e-45, 4.2039e-44, 4.3440e-44],
          [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]],
 
         [[2.3962e-43, 4.2039e-45, 1.4013e-45, 1.4013e-45],
          [7.0065e-45, 4.4842e-44, 0.0000e+00, 0.0000e+00],
          [0.0000e+00, 0.0000e+00, 1.2612e-43, 2.8026e-45]],
 
         [[1.4013e-45, 1.4013e-45, 0.0000e+00, 2.8026e-45],
          [0.0000e+00, 0.

In [ ]:
x1 = torch.FloatTensor([1, 2, 3, 4])
x2 = torch.FloatTensor([2, 3, 4, 5])
torch.dot(x1, x2)


tensor(40.)

In [ ]:
x1 = torch.FloatTensor(3, 4)
x1, x1.t(), torch.t(x1)

(tensor([[7.0841e-28, 0.0000e+00, 0.0000e+00, 1.5046e-36],
         [9.3468e-33, 0.0000e+00, 1.0842e-19, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]]),
 tensor([[7.0841e-28, 9.3468e-33, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 1.0842e-19, 0.0000e+00],
         [1.5046e-36, 0.0000e+00, 0.0000e+00]]),
 tensor([[7.0841e-28, 9.3468e-33, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 1.0842e-19, 0.0000e+00],
         [1.5046e-36, 0.0000e+00, 0.0000e+00]]))

In [ ]:
x1 = torch.FloatTensor(10, 3, 4)
x1.size(), torch.transpose(x1, 1, 2).size(), x1.transpose(1, 2).size()

(torch.Size([10, 3, 4]), torch.Size([10, 4, 3]), torch.Size([10, 4, 3]))

In [ ]:
import torch

A = torch.tensor([
    [2., 0.],
    [0., 1.]
])

eigvals, eigvecs = torch.linalg.eig(A)
eigvals, eigvecs

(tensor([2.+0.j, 1.+0.j]),
 tensor([[1.+0.j, 0.+0.j],
         [0.+0.j, 1.+0.j]]))